# This is a basic workflow to help you get started with GitHub CI using ActivePython
name: ActivePython application on GitHub CI

# Setting up Cache directory and ActiveState Platform API key
env:
  ACTIVESTATE_CLI_CACHEDIR: ${{ github.workspace }}/.cache        
  ACTIVESTATE_API_KEY: ${{ secrets.ACTIVESTATE_API_KEY }}  
  
# Controls when the action will run. Triggers the workflow on push events on the default branch 
on: [push]

# A CI workflow  is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on (this one is a matrix build)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Building on both Windows and Linux(Ubuntu) simultaneously 
        os: [windows-latest]
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Deploy project
      run: .github/workflows/state.exe deploy MyOrg/learn-python
    - name: Lint with pylint
      run: pylint src
    - name: Lint with flake8
      run: flake8 src --statistics --count
    # Running project tests using pytest on ActivePython
    - name: Test with pytest
      run: pytest
